server:
  port: 10880
dubbo:
  application:
    name: tanhua-server
  registry:
    address: zookeeper://10.10.20.22:2181
  consumer:
    check: false
# log
logging:
  level:
    root: info
    com:
      tanhua: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %msg - %logger{15}%n\'
tanhua:
  sms:
    validateCodeTemplateCode: SMS_204761533
    signName: 传智播客
    parameterName: code
    accessKeyId: LTAI4FynsGS7V2bPJqQqrzhH
    accessKeySecret: c9fMcE7W8njMFNLJNJQT2vn5A0J1ey
  redisValidateCodeKeyPrefix: VALIDATECODE_
  secret: 76bd425b6f29f7fcc2e0bfc286043df1
  oss:
    endpoint: http://oss-cn-shenzhen.aliyuncs.com
    bucketName: tanhua107
    url: https://tanhua107.oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI4FynsGS7V2bPJqQqrzhH
    accessKeySecret: c9fMcE7W8njMFNLJNJQT2vn5A0J1ey
  face:
    appId: 23634077
    apiKey: 9Gw8kYfBC0HSI4VvD1dRdTKj
    secretKey: m2BryeIGtm3je7enLbM78hAX9dZ3MreX
  # im
  huanxin:
    url: http://a1.easemob.com/
    orgName: 1112190901181842
    appName: tanhua107
    clientId: YXA6DmVggstiTmSSi_dWvqeoCg
    clientSecret: YXA6PSvRviM513TuJLAeFTtef9Th4wo
# redis
spring:
  redis:
    host: 10.10.20.22
    port: 6379
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  #缩略图生成参数
  thumb-image:
    width: 150
    height: 150
  #TrackerList参数,支持多个
  tracker-list: 10.10.20.22:22122
  web-server-url: http://10.10.20.22:8888/
rocketmq:
  name-server: 10.10.20.22:9876
  producer:
    group: tanhua
